name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Log in to Azure CLI
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 3. Build and push Docker image to Azure Container Registry (ACR)
    - name: Build and push Docker image
      run: |
        docker build -t flask-app .
        docker tag flask-app proyectoinfracontmau.azurecr.io/flask-app:latest
        echo "${{ secrets.AZURE_ACR_PASSWORD }}" | docker login proyectoinfracontmau.azurecr.io --username proyectoinfracontmau --password-stdin
        docker push proyectoinfracontmau.azurecr.io/flask-app:latest

    # 4. Deploy the image to Azure Web App for Containers
    - name: Deploy to Azure Web App
      run: |
        az webapp config container set \
          --name AppConte \
          --resource-group MV_group \
          --docker-custom-image-name proyectoinfracontmau.azurecr.io/flask-app:latest
